export const PAYMENT_METHODS = ["Zelle", "Cash", "Venmo", "Direct Booking", "Stripe"];

export const DEFAULT_SETTINGS = {
  appName: "Ritz Reservations",
  defaultRetailPrice: 3000,
  cleaningFee: 170,
  discountTiers: [
    { nights: 2, discount: 30 },
    { nights: 3, discount: 35 },
    { nights: 4, discount: 40 },
    { nights: 5, discount: 50 },
  ],
  hotelName: "The Ritz-Carlton",
  hotelAddress: "",
  homePageVariant: "classic",
  webhookUrl: "https://n9n.aquaskals.com/webhook-test/get-a-quota",
  webhookEnabled: true,
  emailAlertsEnabled: false,
  quoteAlertEnabled: true,
  priceSentGuestEmailEnabled: true,
  priceSentStaffAlertEnabled: false,
  paymentSubmittedAlertEnabled: false,
  bookingRequestHotelAlertEnabled: false,
  bookingConfirmedHotelAlertEnabled: false,
  bookingConfirmedHotelAlertAttachments: [],
  staffEmailRecipients: [],
  hotelEmailRecipients: [],
  roomTypes: [
    { name: "Deluxe Ocean View, 1 King, Sofa Bed, Ocean View", hidden: false },
    { name: "Ocean Front Suite, 1 King, Living Area, Ocean Front", hidden: false },
    { name: "Club Level, 2 Queens, City View", hidden: false },
    { name: "Presidential Suite, 1 King, Full Kitchen, Ocean View", hidden: false },
  ],
  paymentMethods: [
    { name: "Zelle", instructions: "Send payment via Zelle to: ritz@example.com", hidden: false },
    { name: "Cash", instructions: "Cash payments accepted in person only.", hidden: false },
    { name: "Venmo", instructions: "Send payment via Venmo to: @ritz-reservations", hidden: false },
    { name: "Direct Booking", instructions: "Contact front desk for direct booking payment.", hidden: false },
    { name: "Stripe", instructions: "A payment link will be sent to your email.", hidden: false },
  ],
};
